---
- hosts: localhost
  vars:
    git_repo: "https://github.com/prabhuu31/Angular-BareBones.git"
    branch: "{{BRANCH_NAME}}"
    repo_name: "bone"
  tasks:
  - name: Checkout code from git
    git:
      repo: "{{git_repo}}"
      version: "{{BRANCH_NAME}}"
      dest: "{{repo_name}}"
      clone: yes
      update: yes

  - name: Installing Dependencies
    shell: npm install 
    args:
      chdir: /home/prabhu/bones

  - name: Build
    shell: ng build   
    args:
      chdir: /home/prabhu/bones

  - name: Deploy
    shell: ng serve 
    args:
      chdir: /home/prabhu/bones
    
